<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Gallery;
use Illuminate\Support\Facades\Storage;

class GallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $galleries = [
            [
                'title' => 'Kegiatan MPLS 2024',
                'description' => 'Foto-foto kegiatan Masa Pengenalan Lingkungan Sekolah tahun 2024',
                'category' => 'kegiatan',
                'subcategory' => 'mpls',
                'image_path' => 'galleries/mpls-2024.jpg',
                'thumbnail_path' => 'galleries/thumbnails/mpls-2024.jpg',
                'original_filename' => 'mpls-2024.jpg',
                'file_size' => '2.5MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Sekolah']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => true,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['mpls', 'siswa-baru', 'pengenalan']),
                'published_at' => now(),
            ],
            [
                'title' => 'Upacara Bendera',
                'description' => 'Dokumentasi upacara bendera rutin setiap hari Senin',
                'category' => 'upacara',
                'subcategory' => 'rutin',
                'image_path' => 'galleries/upacara-bendera.jpg',
                'thumbnail_path' => 'galleries/thumbnails/upacara-bendera.jpg',
                'original_filename' => 'upacara-bendera.jpg',
                'file_size' => '1.8MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Lapangan Sekolah']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => false,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['upacara', 'bendera', 'rutin']),
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Lomba Basket Antar Kelas',
                'description' => 'Kompetisi basket antar kelas yang diadakan setiap semester',
                'category' => 'olahraga',
                'subcategory' => 'basket',
                'image_path' => 'galleries/lomba-basket.jpg',
                'thumbnail_path' => 'galleries/thumbnails/lomba-basket.jpg',
                'original_filename' => 'lomba-basket.jpg',
                'file_size' => '3.2MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Lapangan Basket']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => true,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['basket', 'kompetisi', 'olahraga']),
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Pentas Seni Budaya',
                'description' => 'Pertunjukan seni dan budaya siswa dalam rangka HUT RI',
                'category' => 'seni',
                'subcategory' => 'budaya',
                'image_path' => 'galleries/pentas-seni.jpg',
                'thumbnail_path' => 'galleries/thumbnails/pentas-seni.jpg',
                'original_filename' => 'pentas-seni.jpg',
                'file_size' => '2.1MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Aula Sekolah']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => true,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['seni', 'budaya', 'hut-ri']),
                'published_at' => now()->subDays(15),
            ],
            [
                'title' => 'Kegiatan Pramuka',
                'description' => 'Aktivitas ekstrakurikuler pramuka dan perkemahan',
                'category' => 'ekstrakurikuler',
                'subcategory' => 'pramuka',
                'image_path' => 'galleries/kegiatan-pramuka.jpg',
                'thumbnail_path' => 'galleries/thumbnails/kegiatan-pramuka.jpg',
                'original_filename' => 'kegiatan-pramuka.jpg',
                'file_size' => '2.8MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Lapangan Sekolah']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => false,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['pramuka', 'perkemahan', 'ekstrakurikuler']),
                'published_at' => now()->subDays(20),
            ],
            [
                'title' => 'Workshop Teknologi',
                'description' => 'Pelatihan teknologi untuk siswa dalam rangka pengembangan skill',
                'category' => 'pendidikan',
                'subcategory' => 'workshop',
                'image_path' => 'galleries/workshop-teknologi.jpg',
                'thumbnail_path' => 'galleries/thumbnails/workshop-teknologi.jpg',
                'original_filename' => 'workshop-teknologi.jpg',
                'file_size' => '1.9MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Lab Komputer']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => false,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['workshop', 'teknologi', 'pelatihan']),
                'published_at' => now()->subDays(25),
            ],
            [
                'title' => 'Kegiatan OSIS',
                'description' => 'Berbagai kegiatan yang diorganisir oleh OSIS',
                'category' => 'osis',
                'subcategory' => 'kegiatan',
                'image_path' => 'galleries/kegiatan-osis.jpg',
                'thumbnail_path' => 'galleries/thumbnails/kegiatan-osis.jpg',
                'original_filename' => 'kegiatan-osis.jpg',
                'file_size' => '2.3MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Aula Sekolah']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => true,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['osis', 'organisasi', 'kegiatan']),
                'published_at' => now()->subDays(30),
            ],
            [
                'title' => 'Konseling BK',
                'description' => 'Kegiatan konseling dan bimbingan karir untuk siswa',
                'category' => 'konseling',
                'subcategory' => 'bk',
                'image_path' => 'galleries/konseling-bk.jpg',
                'thumbnail_path' => 'galleries/thumbnails/konseling-bk.jpg',
                'original_filename' => 'konseling-bk.jpg',
                'file_size' => '1.5MB',
                'mime_type' => 'image/jpeg',
                'width' => 1920,
                'height' => 1080,
                'metadata' => json_encode(['camera' => 'Canon EOS', 'location' => 'Ruang BK']),
                'uploaded_by_role' => 'admin',
                'uploaded_by_id' => 1,
                'is_featured' => false,
                'is_public' => true,
                'status' => 'published',
                'tags' => json_encode(['konseling', 'bk', 'bimbingan']),
                'published_at' => now()->subDays(35),
            ],
        ];

        foreach ($galleries as $galleryData) {
            Gallery::create($galleryData);
        }

        $this->command->info('Gallery seeder completed successfully!');
    }
}
