<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MataPelajaran;

class MataPelajaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mataPelajaran = [
            // Kelompok A (Wajib)
            [
                'kode' => 'PAI',
                'nama' => 'Pendidikan Agama Islam',
                'deskripsi' => 'Pendidikan agama Islam dan budi pekerti',
                'kelompok' => 'A',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 2,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'PKN',
                'nama' => 'Pendidikan Pancasila dan Kewarganegaraan',
                'deskripsi' => 'Pendidikan kewarganegaraan dan pancasila',
                'kelompok' => 'A',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 2,
                'jam_per_semester' => 36,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 3,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'BIN',
                'nama' => 'Bahasa Indonesia',
                'deskripsi' => 'Bahasa Indonesia sebagai bahasa nasional',
                'kelompok' => 'A',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 4,
                'jam_per_semester' => 72,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 4,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'MTK',
                'nama' => 'Matematika',
                'deskripsi' => 'Matematika dasar dan terapan',
                'kelompok' => 'A',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 4,
                'jam_per_semester' => 72,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 5,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'BING',
                'nama' => 'Bahasa Inggris',
                'deskripsi' => 'Bahasa Inggris sebagai bahasa internasional',
                'kelompok' => 'A',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 6,
                'status_aktif' => true,
                'created_by' => 1,
            ],

            // Kelompok B (Wajib)
            [
                'kode' => 'SEN',
                'nama' => 'Seni Budaya',
                'deskripsi' => 'Seni dan budaya Indonesia',
                'kelompok' => 'B',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 2,
                'jam_per_semester' => 36,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 7,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'PJOK',
                'nama' => 'Pendidikan Jasmani, Olahraga dan Kesehatan',
                'deskripsi' => 'Pendidikan jasmani dan kesehatan',
                'kelompok' => 'B',
                'sub_kelompok' => 'Wajib',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => true,
                'is_peminatan' => false,
                'tingkat_kelas' => 'X,XI,XII',
                'guru_id' => 8,
                'status_aktif' => true,
                'created_by' => 1,
            ],

            // Kelompok C (Peminatan IPA)
            [
                'kode' => 'FIS',
                'nama' => 'Fisika',
                'deskripsi' => 'Ilmu fisika dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPA',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 9,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'KIM',
                'nama' => 'Kimia',
                'deskripsi' => 'Ilmu kimia dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPA',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 10,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'BIO',
                'nama' => 'Biologi',
                'deskripsi' => 'Ilmu biologi dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPA',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 11,
                'status_aktif' => true,
                'created_by' => 1,
            ],

            // Kelompok C (Peminatan IPS)
            [
                'kode' => 'GEO',
                'nama' => 'Geografi',
                'deskripsi' => 'Ilmu geografi dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPS',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 12,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'EKO',
                'nama' => 'Ekonomi',
                'deskripsi' => 'Ilmu ekonomi dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPS',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 13,
                'status_aktif' => true,
                'created_by' => 1,
            ],
            [
                'kode' => 'SOS',
                'nama' => 'Sosiologi',
                'deskripsi' => 'Ilmu sosiologi dan aplikasinya',
                'kelompok' => 'C',
                'sub_kelompok' => 'Peminatan IPS',
                'jam_per_minggu' => 3,
                'jam_per_semester' => 54,
                'kkm' => 75,
                'is_wajib' => false,
                'is_peminatan' => true,
                'tingkat_kelas' => 'XI,XII',
                'guru_id' => 14,
                'status_aktif' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($mataPelajaran as $data) {
            MataPelajaran::create($data);
        }

        $this->command->info('Mata Pelajaran seeder completed successfully!');
    }
}
